### ISSUE TITLE
links between RGs

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#11]
## background

 - display related RGs on individual RG's page
 - cross-connections between more general & more specific RGs --> enrich the hierarchy of RGs beyond 'just' the levels

## TODO 

 - add links to other RGs to each RG (as a list of links)
 - enrich links to other RGs by providing the 'type'  of relationship, for example (_these are really just examples, think of what kinds of relationships make sense_):
   - 'broader'/'narrower'
   - 'example' -> a level 3 RG of a specific person could be an 'example' for the RG on Ambtenaren on level 2
   - geography broader/narrower; something like 'contains'
   - 'part of' -> for example a level 3 RG could be about a person that was/is 'part of' an institution that also has an RG on level 3
   - 'see also' -> could be a more generic kind of relationship that simply says that RG X contains more information about the topic of RG Y
   - etc ...
  - best practice: the more relationships between RGs, the merrier; especially when those relationship are distinguished by types --> trying to exhaustively think of the possible pairs of relationships between RGs can also help with mapping out the types of relationships that are needed (see list of examples above)
  - bonus: it _is_ valid to add the same RG twice in the list of relations of an RG, if there are two different relation types; e.g. RG Y is related to RG X by '
  - describing inverse relationships is valid and can add useful information; e.g. if RG X is 'broader' than RG Y, then RG Y is 'narrower' to RG X (in the 'broader'/'narrower' case, adding the inverse relationship isn't strictly necessary because 'broader' is the obvious inverse of 'narrower'; but think about 'example of', what's the inverse of that?) 

## TBD

 -   which vocabulary to use for the relationships between guides? should it be controlled? (links to controlled vocabulary could simplify modeling)
 - are there relationship types that are needed for front-end functionality? can different types even be displayed/communicated to users? 

## YAML examples

```
Title: "SomeTitle"

RelatedGuides: 
  - "AnotherRG":
        link: "niveau2/AnotherRG_20240523.yaml"
        rel_type: "http://www.example.org"

  - "AThirdRG":
        link: "niveau3/AThirdRG_20240523.yaml"
        rel_type: "http://www.example.org"


```
